### ISSUE TITLE
Pretrained Model for ShanghaiTech dataset

### ISSUE THREAD

**Issue by roystonrodrigues** [StevenLiuWen/ano_pred_cvpr2018#10]
Please provide the pre-trained models for ShanghaiTech dataset

**Comment by roystonrodrigues** [comment]
I request the authors to please provide the pre-trained models for the ShangaiTech dataset.

**Comment by zachluo** [comment]
@roystonrodrigues ok, We will upload the models in few days.

**Comment by StevenLiuWen** [comment]
@roystonrodrigues https://1drv.ms/f/s!AjjUqiJZsj8wuVfJUcG2qENLAIKl, here is the pretrained ShanghaiTech model

**Comment by roystonrodrigues** [comment]
Thanks for sharing the pre-trained models.

**Comment by wblyqq** [comment]
> Thanks for sharing the pre-trained models.
Do you have pre-trainede model for ucsd ped1 and ped2

**Comment by Jimjipeng** [comment]
> @roystonrodrigues https://1drv.ms/f/s!AjjUqiJZsj8wuVfJUcG2qENLAIKl, here is the pretrained ShanghaiTech model

an invalid link！
