### ISSUE TITLE
在运行train.py过程中出现tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: low >= high

### ISSUE THREAD

**Issue by poweryin** [StevenLiuWen/ano_pred_cvpr2018#14]
刘博士，你好，谢谢你分享代码资源给我们。我在运行程序train.py过程中出现以下错误，找不到解决的办法，想麻烦你百忙之中帮我看下是什么问题。tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: low >= high
         [[Node: PyFunc = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT], token="pyfunc_1"](arg0)]]
         [[Node: dataset/IteratorGetNext = IteratorGetNext[output_shapes=[[?,256,256,15]], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](dataset/OneShotIterator)]]
         [[Node: dataset/IteratorGetNext/_117 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_44_dataset/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by shz1314** [comment]
内存不够了把  把打他        dataset = dataset.prefetch(buffer_size=100)
        dataset = dataset.shuffle(buffer_size=100).batch(batch_size)
buffer_size改小一点

**Comment by Jolntu** [comment]
In my experience there is a problem with my training set

**Comment by wangwen39** [comment]
I met the same problem when I tried to training in another dataset, and I have tried to set the buffer size=1, but this seems didn't work for me when the training Sudden disrupt after iter step 50.
