### ISSUE TITLE
Why comment out this line: distance = 1 - distance  ??

### ISSUE THREAD

**Issue by Blssel** [StevenLiuWen/ano_pred_cvpr2018#18]
Hi, I'm curious about that why you comment out this line of code: https://github.com/StevenLiuWen/ano_pred_cvpr2018/blob/master/Codes/evaluate.py#L334 ? I think it should be right with it added.

**Comment by pangwenfeng** [comment]
I also can't understand this operation,  so can you explain it now?

**Comment by zachluo** [comment]
@pangwenfeng @Blssel We normalize PSNR into normal score (higher PSNR means higher score) in this paper, but we normalize reconstruction error into normal score (higher error means lower score) in iccv2017 paper.  We share some codes for these two papers, so don't worry about that.
