### ISSUE TITLE
关于分块识别器的疑问

### ISSUE THREAD

**Issue by pangwenfeng** [StevenLiuWen/ano_pred_cvpr2018#19]
你好，非常感谢你的开源代码！我想请教一下，在论文中，训练时你们使用了分块识别器(patch discriminator)，但在源码中，你们好像没有分块，而是pix2pix的识别器，所以想请教一下是我理解错了代码还是pix2pix的效果会更好？谢谢不吝指教～

**Comment by StevenLiuWen** [comment]
pix2pix.py里面的discriminator是patch GAN的实现
