### ISSUE TITLE
About training on the new dataset

### ISSUE THREAD

**Issue by shz1314** [StevenLiuWen/ano_pred_cvpr2018#20]
博士您好：
       如果我想要在新的数据集上训练，那我应该怎么构建我的数据集呢，我看您生成了.MAT文件。有相应的参考或者制作训练数据集的方法吗？

**Comment by shz1314** [comment]
我下载了您shanghai的数据集，训练数据集还是视频格式，希望你能提供从 视频数据集  到   模型训练数据集 的方法和代码！非常感谢！！

**Comment by StevenLiuWen** [comment]
@shz1314 .mat文件是测试的时候用的，里面有每一帧是正常还是异常的label，训练的时候只要保证里面的训练视频全都是正常就行了（至于什么是正常，具体场景和业务决定的，例如你在所在的场景是幼儿园，在园内骑单车不允许的，小朋友跌倒是异常，也许只有小朋友玩耍之类的才是正常）；直接用视频训练的话，需要写一个修改一下uilts下面的DataLoader这个类，用cv2.VideoCapture之类的读取每一个batch
