### ISSUE TITLE
Any mistake in training set of ShanghaiTech dataset?

### ISSUE THREAD

**Issue by fjchange** [StevenLiuWen/ano_pred_cvpr2018#21]
The moving objets in videos of ShanghaiTech dataset are blurry.
![image](https://user-images.githubusercontent.com/22427196/49630176-f7a11e00-fa27-11e8-899b-95df96c7ce2d.png)

**Comment by StevenLiuWen** [comment]
@fjchange **Windows media player** may result mistake (decode h264), please use other Players, such as **PotPlayer** or **VCL** to play these videos.
