### ISSUE TITLE
run demo

### ISSUE THREAD

**Issue by LakyTT** [StevenLiuWen/ano_pred_cvpr2018#22]
Hi,thanks for your inspiring work. And  I want to know how to run demo  like in https://www.youtube.com/watch?v=M--wv-Y_h0A

**Comment by LakyTT** [comment]
looking forward to your reply

**Comment by StevenLiuWen** [comment]
@LakyTT We just run the `inference.py` and save the PSNR, SCORE, GTs and Predicted Frames, then we visualize all these by matplotlib.

**Comment by woshizhangcheng** [comment]
SCORE is PSNR???

**Comment by zachluo** [comment]
@nobody-cheng We do not normalize PSNR to score for real application.
