### ISSUE TITLE
Training on new dataset

### ISSUE THREAD

**Issue by tahmidzbr** [StevenLiuWen/ano_pred_cvpr2018#23]
Hi,
Many thanks for your great work!
Can you please help with code if i want to train your algorithm on my own dataset?
-
tahmidzbr

**Comment by MillayWang** [comment]
It will help if you look at what the original dataset file contains. You have to add some items in hyper_params.ini and evaluate.py to make your dataset have those parameters like original datasets. You may also need to label ground truth (.mat file) of abnormal behaviors of your own data during evaluating the auc.
