### ISSUE TITLE
flownet input / aspect ratio

### ISSUE THREAD

**Issue by wr0112358** [StevenLiuWen/ano_pred_cvpr2018#24]
The input to the two flownet models is distorted from aspect ratio 1:1(256x256) to 384x512. I understand that flownet needs inputs sizes dividable by 64.
I am trying to understand the reason for this? Why not just pad with zeros to avoid the distortion?

[https://github.com/StevenLiuWen/ano_pred_cvpr2018/blob/master/Codes/models.py#L24](url)

**Comment by StevenLiuWen** [comment]
@wr0112358 [Here](https://github.com/sampepose/flownet2-tf) is the implementation of FlowNet that we use, and in its implementation, the input size must be 384 x 512 (or (k * 192) x (k * 256)). For convenience, we resize the image from 256 x 256 to 384 x 512.
