### ISSUE TITLE
List of Anamolies

### ISSUE THREAD

**Issue by guruvishnuvardan** [StevenLiuWen/ano_pred_cvpr2018#26]
Hi,

What are kind of video Anamolies that are detected in the pretrained model?

Thanks
Guru

**Comment by zachluo** [comment]
@guruvishnuvardan That depends on the dataset. For the definition of CUHK Avenue and UCSD Ped, you can refer to the paper. Actually, we only model the normal behavior of walking so that any abnormal actions can be captured by our model.
