### ISSUE TITLE
About Norm of Regular Score (Maybe better the performance)

### ISSUE THREAD

**Issue by fjchange** [StevenLiuWen/ano_pred_cvpr2018#27]
https://github.com/StevenLiuWen/ano_pred_cvpr2018/blob/d9b1a6094ada005d09206cad0544288b8f7e2410/Codes/evaluate.py#L416

As the code shows, the scores are normalized every video clips, which makes the anomaly standard vary at each clips.
I make it norm for only one time for all the SCORES, and the result better than the paper with 85%+ AUC
[my_re-implementation](https://github.com/fjchange/pytorch_ano_pre)

        `for i in range(num_videos):
            distance = psnr_records[i]
            #if NORMALIZE:
                #distance = (distance-distance.min())/distance.max()  # distances = (distance - min) / (max - min)
                #distance /= distance.max()
                # distance = 1 - distance

            scores = np.concatenate((scores, distance[DECIDABLE_IDX:]), axis=0)
            labels = np.concatenate((labels, gt[i][DECIDABLE_IDX:]), axis=0)

        if NORMALIZE:
            scores-=scores.min()
            scores/=scores.max()
`

**Comment by zachluo** [comment]
@fjchange Thanks for pointing that. We also observed this trick, but found it favors different papers. So here we take the same normalization on all of our papers.

**Comment by fjchange** [comment]
@zachluo Moreover, I found that if I do not modify the norm, the result seem hard to converge.
( I replace FlownetSD with LiteFlownet ) 
I wonder whether you have the problem as I met. Thx

**Comment by fjchange** [comment]
@zachluo The input of flownet2-SD is BGR, but it seems flownet2-tf use RGB instead. Is it a trick, or just a mistake? 
If I input as RGB, sometimes the model will trapping into outputting black images, it seems the flow loss is misleading.
Could you explain it? Many thanks.
