### ISSUE TITLE
Hi，how to run the code with CPU version

### ISSUE THREAD

**Issue by DengMiao55** [StevenLiuWen/ano_pred_cvpr2018#28]
![_EQ6UZ(MZNP}63T$J8YAK~E](https://user-images.githubusercontent.com/45617744/55729487-cde51b80-5a48-11e9-829b-5b7cfdcf0e92.png)

**Comment by musicshmily** [comment]
同问？？？

**Comment by StevenLiuWen** [comment]
pip install tensorlow==1.4.1 (and do not install tensorflow-gpu version)
