### ISSUE TITLE
如何训练自己的数据集？

### ISSUE THREAD

**Issue by jijiangyan** [StevenLiuWen/ano_pred_cvpr2018#33]
您好，很高兴您能够开源这么优秀的代码。想请教您一个问题，如何训练自己的数据集呢？我想用您的方法做视频预测，下载ped1数据集，有个mat文件？请问mat文件如何生成，或者含义是什么？
期待您的回复！

**Comment by a726** [comment]
> 您好，很高兴您能够开源这么优秀的代码。想请教您一个问题，如何训练自己的数据集呢？我想用您的方法做视频预测，下载ped1数据集，有个mat文件？请问mat文件如何生成，或者含义是什么？
> 期待您的回复！

您好，我也遇到了同样的问题，请问您解决了没有？
还有一个问题就是我在运行inference.py的时候显示
Init global successfully!
waiting for models...
##### optimal result and model = dataset = None, loss file = None, auc = -inf
waiting for models...
##### optimal result and model = dataset = None, loss file = None, auc = -inf
之后的都是这样，数据集还有损失函数都是空的，您知道这是什么问题吗？
期待您的回复!

**Comment by Javinciii** [comment]
> > 您好，很高兴您能够开源这么优秀的代码。想请教您一个问题，如何训练自己的数据集呢？我想用您的方法做视频预测，下载ped1数据集，有个mat文件？请问mat文件如何生成，或者含义是什么？
> > 期待您的回复！
> 
> 您好，我也遇到了同样的问题，请问您解决了没有？
> 还有一个问题就是我在运行inference.py的时候显示
> Init global successfully!
> waiting for models...
> 
> ##### optimal result and model = dataset = None, loss file = None, auc = -inf
> waiting for models...
> 
> ##### optimal result and model = dataset = None, loss file = None, auc = -inf
> 之后的都是这样，数据集还有损失函数都是空的，您知道这是什么问题吗？
> 期待您的回复!

你按照说明把数据集和模型解压在正确位置了吗？

**Comment by a726** [comment]
您好！很高兴收到您的回复！最近在学习这篇文章和代码，遇到以下几个问题想请教您：
1.我发现在evaluate.py这个文件中，测试用的是shanghaitech这个数据集，这个数据集里面的文件太大了，在百度云盘下载的很慢，还有一个没有下载好，是因为这个原因导致我的结果是空的？
2.如果我想用其他的数据集测试，例如avenue数据集，它的例如您给的shanghaitech中test_frame_mask文件之类的文件要怎么生成？
3.代码中出现的ped1（2）.mat文件是怎么样生成的（是用matlab直接把数据库中的视频直接读取存成mat文件吗），都有什么要求；还有enter.mat和exit.mat都是什么文件？
最近在学习这篇文章和代码，可能之后还会有问题需要请教，期待您的回复！







---原始邮件---
发件人: "Javinciii"<notifications@github.com&gt;
发送时间: 2019年9月18日(星期三) 晚上7:14
收件人: "StevenLiuWen/ano_pred_cvpr2018"<ano_pred_cvpr2018@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Xiaoyuan Zhang"<306835421@qq.com&gt;;
主题: Re: [StevenLiuWen/ano_pred_cvpr2018] 如何训练自己的数据集？ (#33)


  
您好，很高兴您能够开源这么优秀的代码。想请教您一个问题，如何训练自己的数据集呢？我想用您的方法做视频预测，下载ped1数据集，有个mat文件？请问mat文件如何生成，或者含义是什么？
 期待您的回复！
  
您好，我也遇到了同样的问题，请问您解决了没有？
 还有一个问题就是我在运行inference.py的时候显示
 Init global successfully!
 waiting for models...
 
optimal result and model = dataset = None, loss file = None, auc = -inf
 
waiting for models...
 
optimal result and model = dataset = None, loss file = None, auc = -inf
 
之后的都是这样，数据集还有损失函数都是空的，您知道这是什么问题吗？
 期待您的回复!
  
你按照说明把数据集和模型解压在正确位置了吗？

**Comment by a726** [comment]
> > > 您好，很高兴您能够开源这么优秀的代码。想请教您一个问题，如何训练自己的数据集呢？我想用您的方法做视频预测，下载ped1数据集，有个mat文件？请问mat文件如何生成，或者含义是什么？
> > > 期待您的回复！
> > 
> > 
> > 您好，我也遇到了同样的问题，请问您解决了没有？
> > 还有一个问题就是我在运行inference.py的时候显示
> > Init global successfully!
> > waiting for models...
> > ##### optimal result and model = dataset = None, loss file = None, auc = -inf
> > waiting for models...
> > ##### optimal result and model = dataset = None, loss file = None, auc = -inf
> > 之后的都是这样，数据集还有损失函数都是空的，您知道这是什么问题吗？
> > 期待您的回复!
> 
> 你按照说明把数据集和模型解压在正确位置了吗？

您好，请问关于flownet都要下载什么？是不是要下预先训练的权重（4.4g的文件？），您要是有是否方便发我一份，我在网上找的链接都失效了。非常感谢您，期待您的回复！

**Comment by Javinciii** [comment]
> > > > 您好，很高兴您能够开源这么优秀的代码。想请教您一个问题，如何训练自己的数据集呢？我想用您的方法做视频预测，下载ped1数据集，有个mat文件？请问mat文件如何生成，或者含义是什么？
> > > > 期待您的回复！
> > > 
> > > 
> > > 您好，我也遇到了同样的问题，请问您解决了没有？
> > > 还有一个问题就是我在运行inference.py的时候显示
> > > Init global successfully!
> > > waiting for models...
> > > ##### optimal result and model = dataset = None, loss file = None, auc = -inf
> > > waiting for models...
> > > ##### optimal result and model = dataset = None, loss file = None, auc = -inf
> > > 之后的都是这样，数据集还有损失函数都是空的，您知道这是什么问题吗？
> > > 期待您的回复!
> > 
> > 
> > 你按照说明把数据集和模型解压在正确位置了吗？
> 
> 您好，请问关于flownet都要下载什么？是不是要下预先训练的权重（4.4g的文件？），您要是有是否方便发我一份，我在网上找的链接都失效了。非常感谢您，期待您的回复！

不用这么客气，我也是学生。
我看了一下网盘链接是能打开的，里面包含了所有需要的文件。OneDrive打不开是被墙了。
pretains.tar.gz有所有预训练的模型，包括光流。
tensorflow训练出的一个模型包括三个文件：.meta   .index  .data-xxxxx-of-xxxxx，可以根据需要单独下载，但是光流的模型必须下载。
例如ped1.tar.gz文件里是数据，包括训练和测试两部分，.mat和mask里的.npy都是标签，标注了异常所在帧，没有这部分并不影响训练或测试，这是用来算AUC的。如果想算自己数据的AUC需要人工标注生成标签文件。

**Comment by a726** [comment]
谢谢你的回复！光流模型都需要下载什么？（我看代码里有光流的代码，是要下载权重文件吗）是否有链接？方便的话我们加个好友，有问题好向你请教！QQ306835421



---原始邮件---
发件人: "Javinciii"<notifications@github.com&gt;
发送时间: 2019年9月19日(星期四) 下午2:00
收件人: "StevenLiuWen/ano_pred_cvpr2018"<ano_pred_cvpr2018@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Xiaoyuan Zhang"<306835421@qq.com&gt;;
主题: Re: [StevenLiuWen/ano_pred_cvpr2018] 如何训练自己的数据集？ (#33)


    
您好，很高兴您能够开源这么优秀的代码。想请教您一个问题，如何训练自己的数据集呢？我想用您的方法做视频预测，下载ped1数据集，有个mat文件？请问mat文件如何生成，或者含义是什么？
 期待您的回复！
  
您好，我也遇到了同样的问题，请问您解决了没有？
 还有一个问题就是我在运行inference.py的时候显示
 Init global successfully!
 waiting for models...
 
optimal result and model = dataset = None, loss file = None, auc = -inf
 
waiting for models...
 
optimal result and model = dataset = None, loss file = None, auc = -inf
 
之后的都是这样，数据集还有损失函数都是空的，您知道这是什么问题吗？
 期待您的回复!
  
你按照说明把数据集和模型解压在正确位置了吗？
  
您好，请问关于flownet都要下载什么？是不是要下预先训练的权重（4.4g的文件？），您要是有是否方便发我一份，我在网上找的链接都失效了。非常感谢您，期待您的回复！
  
不用这么客气，我也是学生。
 我看了一下网盘链接是能打开的，里面包含了所有需要的文件。OneDrive打不开是被墙了。
 pretains.tar.gz有所有预训练的模型，包括光流。
 tensorflow训练出的一个模型包括三个文件：.meta   .index  .data-xxxxx-of-xxxxx，可以根据需要单独下载，但是光流的模型必须下载。
 例如ped1.tar.gz文件里是数据，包括训练和测试两部分，.mat和mask里的.npy都是标签，标注了异常所在帧，没有这部分并不影响训练或测试，这是用来算AUC的。如果想算自己数据的AUC需要人工标注生成标签文件。
