### ISSUE TITLE
download the pretrained models and datasets

### ISSUE THREAD

**Issue by wsz912** [StevenLiuWen/ano_pred_cvpr2018#4]
Hi, Dr. Liu Wen. Could you share a BaiduYun Link about the pretrained models and datasets of this paper ? There are some difficulties about downloading these files from OneDrive. Thanks a lot.

**Comment by StevenLiuWen** [comment]
@wsz1029 Ok, I have uploaded all files to BaiduYun and here is the link https://pan.baidu.com/s/11MfG5g-NaV9Bs2jpNIihHw#list/path=%2F

**Comment by Santana18** [comment]
That server unfortunately provides 13 kb/s at the moment, requiring a 3 days download, while I currently have 7 MB/s avaialble.

Edit: Download failed after 30 minutes

**Comment by songfish** [comment]
But there is no shanghaitech.tar.gz in this link....

**Comment by StevenLiuWen** [comment]
@Santana18 You can have a try on OneDrive, https://onedrive.live.com/?authkey=%21AMqh2fTSemfrokE&id=3705E349C336415F%215109&cid=3705E349C336415F

**Comment by StevenLiuWen** [comment]
@songfish  I have uploaded it just right, you can access it.

**Comment by songfish** [comment]
@StevenLiuWen Thank you very much!
