### ISSUE TITLE
the provided shanghaitech model cant reach 0.72 auc

### ISSUE THREAD

**Issue by tenggyut** [StevenLiuWen/ano_pred_cvpr2018#44]
the provided shanghaitech model cant reach 0.72 auc. use the default training setting also cant reach 0.72 auc on shanghaitech dataset.

Any idea?

**Comment by HuangQingWang** [comment]
i don't know the reason why the author no stand out to solve problem for us!!!

**Comment by zachluo** [comment]
![image](https://user-images.githubusercontent.com/13637932/69781515-69e6b180-11e9-11ea-8041-66c8745eed3d.png)
We can reproduce the reported results.

**Comment by tenggyut** [comment]
Thx your reply!
is the result reproduced by the provided model or your own trained model? What's your training and evaluation settings?

**Comment by zachluo** [comment]
@tenggyut It is reproduced by the provided model. Please refer to the README to get the result.

**Comment by abhishekaich27** [comment]
@zachluo how do we set the training for the Shanghai-Tech dataset? the current format is in form of videos. How do you pre-process this?

**Comment by zzzzyq-18** [comment]
> @tenggyut它是由提供的模型复制的。请参阅 README 以获取结果。

想请问您，shanghaiTech数据集的训练数据，帧率是多少啊
