### ISSUE TITLE
训练自己的数据集，损失一直增长

### ISSUE THREAD

**Issue by woshizhangcheng** [StevenLiuWen/ano_pred_cvpr2018#50]
你好
我拿了17个正常的地铁（包括高峰期和正常人流）视频，数据集均是按照跳2帧切一张图，17个文件夹接近20w的图片库，按照说明进行一些参数设置
--iters   = 80000
--batch = 16
损失图如下，adversarial loss和train_psnr_error generator loss均是越来越大
![Snipaste_2020-06-19_18-17-48](https://user-images.githubusercontent.com/34908468/85122492-3b015d00-b259-11ea-9e0c-48c92e25458c.jpg)
![Snipaste_2020-06-19_18-17-58](https://user-images.githubusercontent.com/34908468/85122494-3ccb2080-b259-11ea-8bf3-16039d44b5d1.jpg)

**Comment by zachluo** [comment]
@nobody-cheng train_psnr_error越高越好，generator loss越低越好，你这不是很正常吗？adversarial loss变大很正常，可以多训练。
