### ISSUE TITLE
Training of U-Net

### ISSUE THREAD

**Issue by kakashiayush** [StevenLiuWen/ano_pred_cvpr2018#53]
can someone tell me that how U-Net is training in this whole code because i am not able to see any code which is used to train U-Net which is predicting a new frame. In research paper they have told that they are training their generator.

**Comment by StevenLiuWen** [comment]
Hi, @kakashiayush，in this paper, the generator is the U-Net, and they are the same thing. https://github.com/StevenLiuWen/ano_pred_cvpr2018/blob/master/Codes/models.py#L15

**Comment by ayushdgupta** [comment]
1-> I already studied this in your paper but my question is you are generating future frames without training your neural network but in your paper you have written about training your generator, I'm not getting this point that how you are training your generator???
2-> And one more thing that you have used tf.train(-----------------------------------) in your code in train.py file. what is that line is doing (i mean that which kind of model or which model that line is training). Please clear these 2 douts of mine.
