### ISSUE TITLE
how to download shanghaitech dataset?

### ISSUE THREAD

**Issue by Tuanzhang911** [StevenLiuWen/ano_pred_cvpr2018#59]
Please give me a download link

1051376930@qq.com

**Comment by Tuanzhang911** [comment]
2112012141@zjut.edu.cn

**Comment by StevenLiuWen** [comment]
@Tuanzhang911 , http://101.32.75.151:8181/dataset/ or Baidupan (https://pan.baidu.com/s/1j0TEt-2Dw3kcfdX-LCF0YQ) with password **i9b3**
