### ISSUE TITLE
the last activation function of the generator

### ISSUE THREAD

**Issue by wsz912** [StevenLiuWen/ano_pred_cvpr2018#7]
Hi, Dr. Liu Wen. I have a problem about the last activation function of the generator. Why dose the last activation function in your code choose tanh rather than Relu? To my knowledge, the original U-net chose ReLu as the last activation function. I'm confused about this change. Could you give me some explanations about this problem? Thanks in advance.

**Comment by StevenLiuWen** [comment]
Since we have normalized the image color space to [-1, 1], so that we use tanh. In many image generation tasks, such as GAN, image-to image translation, cyclegan, next frame prediction and so on, they usually normalize the image color space to [-1, 1] and we just follow them.
