### ISSUE TITLE
why don't you use flownet2 for generating optical flow?

### ISSUE THREAD

**Issue by owliz** [StevenLiuWen/ano_pred_cvpr2018#9]
Hi, Steven. Thanks for your inspiring paper and  code.   
I want to know why you choose flownet-SD rather than flownet2(the final fused model) to generate optical flow. Did flownet2 show poor performance in your experiments?   
Do you think a more accurate optical flow prediction will improve the final detection results?    

Looking forward to your insight.

**Comment by StevenLiuWen** [comment]
FlowNet2 is  an ensemble model (combine, not fully-differentiable, it can not do
